version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    volumes:
      - ./api:/app
      - deps:/app/deps
      - build:/app/_build
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:1234@db/api_dev
    depends_on:
      - db
    command: >
      /bin/sh -c "mix ecto.create && mix ecto.migrate && exec mix phx.server"
  web:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  postgres_data:
  deps:
  build:
