name: Déploiement Docker Compose via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Ajout de la clé SSH
      run: |
        mkdir .ssh
        touch .ssh/id_rsa
        touch .ssh/id_rsa.pub
        echo "${{ secrets.SSH_KEYPRIV }}" > .ssh/id_rsa
        echo "${{ secrets.SSH_KEYPUB }}" > .ssh/id_rsa.pub
        chmod 600 .ssh/id_rsa
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add .ssh/id_rsa

    - name: Déploiement via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/Arthur/project/TimeManager
          sudo docker-compose down
          git pull
          sudo docker-compose up --build -d
